'use client';

import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useSafety } from '../context/SafetyContext';
import { X, Play, Pause, Download, Eye } from 'lucide-react';
import jsPDF from 'jspdf';

export default function IncidentModal() {
  const { showModal, setShowModal, selectedIncident } = useSafety();
  const [videoProgress, setVideoProgress] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);

  useEffect(() => {
    if (showModal) {
      setVideoProgress(0);
      setIsPlaying(false);
    }
  }, [showModal]);

  useEffect(() => {
    let interval;
    if (isPlaying && videoProgress < 100) {
      interval = setInterval(() => {
        setVideoProgress(prev => {
          if (prev >= 100) {
            setIsPlaying(false);
            return 100;
          }
          return prev + 20; // 5 second video = 20% per second
        });
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [isPlaying, videoProgress]);

  const handlePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const handleDownloadReport = () => {
    try {
      const pdf = new jsPDF();
      
      // Set font for better Unicode support
      pdf.setFont('helvetica');
      
      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(255, 184, 0); // Construction yellow
      pdf.text('INCIDENT DETAILED REPORT', 105, 20, { align: 'center' });
      
      // Incident Details
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text('Incident Details:', 20, 40);
      
      pdf.setFontSize(10);
      pdf.setTextColor(200, 200, 200);
      pdf.text(`Type: ${selectedIncident.type.replace('_', ' ').toUpperCase()}`, 20, 50);
      pdf.text(`Severity: ${selectedIncident.severity.toUpperCase()}`, 20, 60);
      pdf.text(`Location: ${selectedIncident.location}`, 20, 70);
      pdf.text(`Time: ${selectedIncident.time}`, 20, 80);
      pdf.text(`Date: ${selectedIncident.date || new Date().toISOString().split('T')[0]}`, 20, 90);
      pdf.text(`Status: ${selectedIncident.status.replace('_', ' ').toUpperCase()}`, 20, 100);
      
      if (selectedIncident.reportedBy) {
        pdf.text(`Reported By: ${selectedIncident.reportedBy}`, 20, 110);
      }
      
      // Description
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text('Description:', 20, 130);
      
      pdf.setFontSize(10);
      pdf.setTextColor(200, 200, 200);
      const description = selectedIncident.description || selectedIncident.title;
      const splitDescription = pdf.splitTextToSize(description, 170);
      pdf.text(splitDescription, 20, 140);
      
      let currentY = 140 + (splitDescription.length * 7) + 10;
      
      // Cost Analysis for Near Miss
      if (selectedIncident.type === 'near_miss') {
        const costSaved = selectedIncident.costSaved || Math.floor(Math.random() * 100000) + 10000;
        const potentialCost = selectedIncident.potentialCost || costSaved;
        
        pdf.setFontSize(12);
        pdf.setTextColor(255, 255, 255);
        pdf.text('Cost Analysis:', 20, currentY);
        
        pdf.setFontSize(10);
        pdf.setTextColor(200, 200, 200);
        pdf.text(`Potential Cost if Accident Occurred: RM ${potentialCost.toLocaleString()}`, 20, currentY + 10);
        pdf.setTextColor(0, 255, 0); // Green for savings
        pdf.text(`Cost Saved by Prevention: RM ${costSaved.toLocaleString()}`, 20, currentY + 20);
        
        // Add visual emphasis
        pdf.setDrawColor(255, 184, 0);
        pdf.setLineWidth(0.5);
        pdf.rect(15, currentY - 5, 180, 35);
        
        currentY += 50;
      }
      
      // Z.AI Analysis
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text('Z.AI Analysis:', 20, currentY);
      
      pdf.setFontSize(10);
      pdf.setTextColor(200, 200, 200);
      const analysisPoints = [
        'No immediate safety hazards detected in the vicinity.',
        'Scaffolding instability identified as root cause.',
        'Recommendation: Immediate inspection of all scaffolding structures.'
      ];
      
      analysisPoints.forEach((point, index) => {
        const splitPoint = pdf.splitTextToSize(`${index + 1}. ${point}`, 170);
        pdf.text(splitPoint, 20, currentY + 10 + (index * 15));
      });
      
      currentY += 60;
      
      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by SafeSite AI - YTL AI Labs', 105, 280, { align: 'center' });
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, 105, 285, { align: 'center' });
      
      // Save with incident details
      const incidentTitle = selectedIncident.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      pdf.save(`incident-detailed-${incidentTitle}-${timestamp}.pdf`);
      
    } catch (error) {
      console.error('Error generating incident PDF:', error);
      alert('Failed to generate incident PDF. Please try again.');
    }
  };

  if (!showModal || !selectedIncident) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4"
        onClick={() => setShowModal(false)}
      >
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          className="bg-dark-surface border border-dark-border rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Modal Header */}
          <div className="flex items-center justify-between p-6 border-b border-dark-border">
            <div>
              <h2 className="text-xl font-bold text-white">Incident Review</h2>
              <p className="text-sm text-gray-400 mt-1">Near Miss Analysis</p>
            </div>
            <button
              onClick={() => setShowModal(false)}
              className="p-2 hover:bg-dark-bg rounded-lg transition-colors"
            >
              <X className="w-5 h-5 text-gray-400" />
            </button>
          </div>

          {/* Modal Content */}
          <div className="p-6 space-y-6">
            {/* Incident Details */}
            <div className="bg-dark-bg rounded-lg p-4">
              <h3 className="text-white font-semibold mb-3">Incident Details</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-gray-400">Type:</span>
                  <span className="text-white ml-2 capitalize">{selectedIncident.type.replace('_', ' ')}</span>
                </div>
                <div>
                  <span className="text-gray-400">Severity:</span>
                  <span className="text-white ml-2 capitalize">{selectedIncident.severity}</span>
                </div>
                <div>
                  <span className="text-gray-400">Location:</span>
                  <span className="text-white ml-2">{selectedIncident.location}</span>
                </div>
                <div>
                  <span className="text-gray-400">Time:</span>
                  <span className="text-white ml-2">{selectedIncident.time}</span>
                </div>
              </div>
              <div className="mt-3">
                <span className="text-gray-400">Description:</span>
                <p className="text-white mt-1">{selectedIncident.title}</p>
              </div>
            </div>

            {/* Evidence Section */}
            <div className="bg-dark-bg rounded-lg p-4">
              <h3 className="text-white font-semibold mb-3">Evidence</h3>
              
              {/* Static Image Placeholder */}
              <div className="mb-4">
                <div className="relative rounded-lg overflow-hidden bg-gray-800 h-48 flex items-center justify-center">
                  <div className="text-center">
                    <Eye className="w-12 h-12 text-gray-600 mx-auto mb-2" />
                    <p className="text-gray-400 text-sm">Incident Scene Image</p>
                    <p className="text-gray-500 text-xs mt-1">Captured at {selectedIncident.time}</p>
                  </div>
                </div>
              </div>

              {/* Simulated Z.AI Video Clip */}
              <div>
                <h4 className="text-white font-medium mb-2 flex items-center">
                  <Play className="w-4 h-4 mr-2 text-construction-yellow" />
                  Z.AI Video Analysis (5s)
                </h4>
                <div className="relative rounded-lg overflow-hidden bg-black h-32">
                  {/* Video Placeholder */}
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center">
                      <div className="w-16 h-16 bg-construction-yellow rounded-full flex items-center justify-center mb-2">
                        <Play className="w-8 h-8 text-black" />
                      </div>
                      <p className="text-white text-sm">AI-Enhanced Video</p>
                    </div>
                  </div>
                  
                  {/* Video Progress Bar */}
                  <div className="absolute bottom-0 left-0 right-0 bg-black/50 p-2">
                    <div className="flex items-center space-x-2">
                      <button
                        onClick={handlePlayPause}
                        className="p-1 bg-construction-yellow rounded text-black"
                      >
                        {isPlaying ? <Pause className="w-3 h-3" /> : <Play className="w-3 h-3" />}
                      </button>
                      <div className="flex-1 bg-gray-700 rounded-full h-1">
                        <motion.div
                          className="bg-construction-yellow h-1 rounded-full"
                          initial={{ width: 0 }}
                          animate={{ width: `${videoProgress}%` }}
                          transition={{ duration: 0.5 }}
                        />
                      </div>
                      <span className="text-xs text-white">
                        {Math.floor(videoProgress / 20)} / 5s
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* AI Analysis */}
            <div className="bg-dark-bg rounded-lg p-4">
              <h3 className="text-white font-semibold mb-3">Z.AI Analysis</h3>
              <div className="space-y-2 text-sm">
                <div className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-green-400 rounded-full mt-1.5"></div>
                  <p className="text-gray-300">No immediate safety hazards detected in the vicinity.</p>
                </div>
                <div className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-yellow-400 rounded-full mt-1.5"></div>
                  <p className="text-gray-300">Scaffolding instability identified as root cause.</p>
                </div>
                <div className="flex items-start space-x-2">
                  <div className="w-2 h-2 bg-blue-400 rounded-full mt-1.5"></div>
                  <p className="text-gray-300">Recommendation: Immediate inspection of all scaffolding structures.</p>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex space-x-3">
              <button className="flex-1 py-2 px-4 bg-construction-yellow text-black rounded-lg font-semibold hover:bg-yellow-400 transition-colors">
                Mark as Resolved
              </button>
              <button className="flex-1 py-2 px-4 bg-dark-bg text-white rounded-lg font-semibold border border-dark-border hover:bg-gray-800 transition-colors">
                Schedule Follow-up
              </button>
              <button
                onClick={handleDownloadReport}
                className="py-2 px-4 bg-dark-bg text-white rounded-lg border border-dark-border hover:bg-gray-800 transition-colors"
                title="Download Detailed Report"
              >
                <Download className="w-4 h-4" />
              </button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}